data:
  config:
    root_folder: /path/to/datasets
    sample_rate: ${sample_rate} # depends on the anonymization model
    batch_size: ${batch_size} # depends on the anonymization model

  datasets:
    eval:
      - vpc2024/datafiles/libri_dev.txt
      - vpc2024/datafiles/libri_test.txt
      - vpc2024/datafiles/IEMOCAP_dev.txt
      - vpc2024/datafiles/IEMOCAP_test.txt
      - vpc2024/datafiles/ls-train-clean-360.txt
    targets:
      - vpc2024/datafiles/libritts-train-other-500_subset.txt

seed: 0
log_dir: logs/private_knnvc
device: cpu # overwritten on runtime

inference:
  run: true # store anonymized utterances; can be true, false or a path to an exp folder
  consistent_targets: false
  gender_conversion: same # same, opposite, or null
  input: # input of the `infer` method of the anonymizer
    spectrogram: spectrogram # key under which the spectrogram can be found
    target: target

target_selection_cfg: spkanon_eval/config/components/target_selection/random.yaml
pipeline_cfg: spkanon_eval/private_knnvc/config.yaml # must clone spkanon_models repo first (see README)
enhance_audio: false
converter_params:
  duration_prediction_weight: 0.7
  n_phone_clusters: 16
  phone_predictor_cls: ConvDecoder
  phone_predictor_ckpt: checkpoints/phone_decoder.pt
  duration_predictor_cls: ConvDecoder
  duration_predictor_ckpt: checkpoints/duration_decoder.pt
  phone_lexicon: private_knnvc/phone_lexicon.txt
